# Mouse Support
set -g mouse on

# Terminal
set -g default-command zsh
set -ga terminal-overrides ",*256col*:Tc"
set -sg escape-time 10
set -g focus-events on
set -g detach-on-destroy off
set -g status-right "#(date +'%Y-%m-%dT%H:%M%z')"
set -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Mode Keys
set -g mode-keys vi

# Scrollback
set -g history-limit 1000000

# Move like in VIM windows
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload configuration file
bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "reloaded tmux configuration"

# Windows
bind-key c new-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

# Sessions
bind-key Space display-popup -E -w 90% -h 90% \
  "zsh -c 'dir=\$(find $HOME -not -path \"*/.*\" -type d 2>/dev/null | fzf --scheme=path --prompt=\"Search project> \" --height=100% --reverse); \
   [ -n \"\$dir\" ] && tmux new-session -d -c \"\$dir\" -s \$(basename \"\$dir\") && tmux switch-client -t \$(basename \"\$dir\")'"

# Session Hooks
set-hook -g session-created "run-shell '
  cd #{pane_current_path}
  if git_root=$(git rev-parse --show-toplevel 2>/dev/null); then
    tmux rename-window -t #{session_name}:0 main \;\
    tmux send-keys -t #{session_name}:main \"yazi\" C-m \;\
    tmux new-window -c #{pane_current_path} \;\
    tmux select-window -t #{session_name}:main
  fi
'"
